import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Providers } from "./Providers/providers";
import AuthProviders from "./Providers/authProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProviders>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </AuthProviders>
      </body>
    </html>
  );
}
